spring.application.name=photoStudio
server.port=8080

# PostgreSQL DataSource (Neon)
# spring.datasource.url=jdbc:postgresql://ep-snowy-firefly-ao3holkd-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
# spring.datasource.username=neondb_owner
# spring.datasource.password=npg_HPpImc6X5ebT

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
# jwt.secret=aravinthPhotographyStudioSuperSecretKey2024JWTSigningKey
# jwt.expiration=86400000

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# Cloudinary Configuration (Credentials via environment variables)
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}
# cloudinary.cloud-name=fknwgvhm
# cloudinary.api-key=429123935655556
# cloudinary.api-secret=iAnQqEaRmi7n8t5fTKtF1rnBdUI
